name: Snowflake Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      - name: Verify Snowflake CLI
        run: snow --version

      - name: Run SQL - Create Table
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snow sql \
            --temporary-connection \
            --account il24358.ap-southeast-1 \
            --user "$SNOWFLAKE_USER" \
            --password "$SNOWFLAKE_PASSWORD" \
            --role SYSADMIN \
            --warehouse COMPUTE_WH \
            --database LUNA_DB \
            --schema LUNA_SH \
            --filename SQL/DEPLOY.SQL

      - name: Run SQL - Insert Data
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snow sql \
            --temporary-connection \
            --account il24358.ap-southeast-1 \
            --user "$SNOWFLAKE_USER" \
            --password "$SNOWFLAKE_PASSWORD" \
            --role SYSADMIN \
            --warehouse COMPUTE_WH \
            --database LUNA_DB \
            --schema LUNA_SH \
            --filename SQL/DEPLOY.SQL
